### ISSUE TITLE
Meeting 01/11: ToDo

### ISSUE THREAD

**Issue by theodruilhe** [killian31/Case_Study_ClimChange#11]
# ToDo
- [x] Convertir les données de Kelvin vers Celsius
- [x] Add a linear regression of medians of mean temperature, max temp and min temp.
- [x] Ligne horizontale partant de la première médiane sur les boxplot pour voir si constant
- [ ] Tester en prenant des points géo précis pour voir si les résultats diffèrent -> on peut utiliser leaflet pour créer un fond de carte avec le relief pour choisir les points
- [x] Histogramme densité de température + voir comment l'histogramme évolue au cours du temps (faire des histogrammes lissés pour les plot sur le même graphique): estimateur à noyau, fonction R existe -> POUR CHAQUE VARIABLE et POUR CHAQUE PAYS.
- [ ] Réfléchir à quelques variables mettre dans un modèle pour expliquer l'évolution du nombre de migrants sortant d'un pays vers un autre (pour chaque destination): températures, ... (à trouver)
- [ ] Chercher des articles biblio
- [x] Présenter tout ça sous forme de pdf
